# Generated by Django 5.2.17 on 2026-09-20 04:51
import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='lastname')),
                ('nickname', models.CharField(max_length=30, verbose_name='nickename')),
                ('member_code', models.CharField(default=accounts.models.generate_member_code, max_length=12, unique=True, verbose_name='password member')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='PIN (แฮช)')),
                ('face_photo', models.ImageField(upload_to=accounts.models.face_photo_path, verbose_name='face')),
                ('face_descriptor', models.JSONField(verbose_name='face descriptor (128 ค่า)')),
                ('consent_pdpa', models.BooleanField(default=False, verbose_name='Consent to the collection of facial images')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of giving consent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'member',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='time')),
                ('success', models.BooleanField(verbose_name='complete')),
                ('fail_reason', models.CharField(blank=True, max_length=20, verbose_name='เหตุผล (ภายใน)')),
                ('sheet_status', models.CharField(choices=[('not_needed', 'ไม่ต้องส่ง'), ('pending', 'รอส่ง'), ('sending', 'กำลังส่ง'), ('sent', 'ส่งแล้ว'), ('failed', 'ส่งไม่สำเร็จ (จะลองใหม่)')], default='not_needed', max_length=12, verbose_name='สถานะส่งชีต')),
                ('sheet_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Number of transmission attempts')),
                ('sheet_last_try', models.DateTimeField(blank=True, null=True, verbose_name='Trying the latest submission.')),
                ('sheet_error', models.CharField(blank=True, max_length=200, verbose_name='Latest sheet errors')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.person')),
            ],
            options={
                'verbose_name': 'History login login log in',
                'verbose_name_plural': 'History login login log in',
                'ordering': ['-created_at'],
            },
        ),
    ]
